# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/shishijie/workspace/project/DPR/dpr/downloads/data/wikipedia_split/psgs_w100.tsv
  id_prefix: 'wiki:'

dpr_stackex_qa:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/zhangfanjin/projects/qa/OAG-AQA/data/kddcup/candidate_papers.tsv
  id_prefix: 'wiki:'