# @package _group_

dpr_wiki:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/shishijie/workspace/project/DPR/dpr/downloads/data/wikipedia_split/psgs_w100.tsv
  id_prefix: 'wiki:'

dpr_stackex_qa:
  _target_: dpr.data.retriever_data.CsvCtxSrc
  file: /home/shishijie/workspace/project/oag-qa/data/stackex_dpr/papers.tsv
  id_prefix: 'wiki:'