# @package _group_

nq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /home/shishijie/workspace/project/DPR/dpr/downloads/data/retriever/qas/nq-test.csv
  #query_special_suffix: '?'

nq_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-train

nq_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.nq-dev

trivia_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-test

trivia_train:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-train

trivia_dev:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.trivia-dev

webq_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.webq-test

curatedtrec_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: data.retriever.qas.curatedtrec-test

stackex_qa_test:
  _target_: dpr.data.retriever_data.CsvQASrc
  file: /home/shishijie/workspace/project/oag-qa/data/stackex_dpr/qa_test.tsv

